// Breed Size Classification Database and Logic

// Enhanced breed size database with comprehensive coverage
const BREED_SIZE_DATABASE = {
  // Small breeds (under 25 lbs / 11 kg)
  small: {
    'affenpinscher': true,
    'chihuahua': true,
    'maltese': true,
    'papillon': true,
    'pomeranian': true,
    'pug': true,
    'shihtzu': true,
    'yorkshire': true,
    'toy': true,
    'havanese': true,
    'pekinese': true,
    'brabancon': true,
    'cotondetulear': true,
    'lhasa': true,
    'schipperke': true,
    'bichon': true,
    'miniature': true,
    'mini': true,
    'japanese': true,
    'silky': true,
    'norfolk': true,
    'norwich': true,
    'cairn': true,
    'west': true,
    'westhighland': true,
    'dandie': true,
    'lakeland': true,
    'sealyham': true,
    'tibetan': true,
    'mexican': true,
    'eskimo': true
  },

  // Medium breeds (25-60 lbs / 11-27 kg)
  medium: {
    'beagle': true,
    'bulldog': true,
    'boston': true,
    'french': true,
    'cocker': true,
    'border': true,
    'australian': true,
    'brittany': true,
    'pointer': true,
    'german': true,
    'basenji': true,
    'whippet': true,
    'corgi': true,
    'cardigan': true,
    'pembroke': true,
    'dachshund': true,
    'shiba': true,
    'keeshond': true,
    'samoyed': true,
    'chow': true,
    'dalmatian': true,
    'boxer': true,
    'vizsla': true,
    'weimaraner': true,
    'standard': true,
    'medium': true,
    'english': true,
    'irish': true,
    'welsh': true,
    'scottish': true,
    'american': true,
    'bedlington': true,
    'fox': true,
    'kerryblue': true,
    'patterdale': true,
    'russell': true,
    'wheaten': true,
    'staffordshire': true,
    'blenheim': true,
    'sussex': true,
    'setter': true,
    'gordon': true,
    'springer': true,
    'clumber': true,
    'finnish': true,
    'lapphund': true,
    'norwegian': true,
    'swedish': true,
    'entlebucher': true,
    'appenzeller': true,
    'kelpie': true,
    'cattledog': true,
    'sheepdog': true,
    'shetland': true,
    'briard': true,
    'bouvier': true,
    'groenendael': true,
    'malinois': true,
    'tervuren': true,
    'saluki': true,
    'borzoi': true,
    'greyhound': true,
    'italian': true,
    'afghan': true,
    'basset': true,
    'blood': true,
    'ibizan': true,
    'plott': true,
    'walker': true,
    'bluetick': true,
    'coonhound': true,
    'redbone': true,
    'otterhound': true,
    'ridgeback': true,
    'rhodesian': true,
    'sharpei': true,
    'akita': true,
    'husky': true,
    'spitz': true,
    'indian': true,
    'pitbull': true,
    'mix': true,
    'cockapoo': true,
    'labradoodle': true,
    'puggle': true,
    'cavapoo': true,
    'segugio': true,
    'waterdog': true,
    'spanish': true,
    'dhole': true,
    'dingo': true,
    'pariah': true,
    'kombai': true,
    'chippiparai': true,
    'gaddi': true,
    'mudhol': true,
    'rajapalayam': true,
    'bakharwal': true,
    'buhund': true,
    'danish': true,
    'frise': true,
    'hound': true,
    'mexicanhairless': true,
    'spaniel': true,
    'terrier': true
  },

  // Large breeds (over 60 lbs / 27+ kg)
  large: {
    'retriever': true,
    'golden': true,
    'labrador': true,
    'chesapeake': true,
    'curly': true,
    'flatcoated': true,
    'shepherd': true,
    'germanshepherd': true,
    'rottweiler': true,
    'doberman': true,
    'great': true,
    'dane': true,
    'mastiff': true,
    'bull': true,
    'newfoundland': true,
    'stbernard': true,
    'leonberg': true,
    'pyrenees': true,
    'bernese': true,
    'swiss': true,
    'mountain': true,
    'malamute': true,
    'komondor': true,
    'kuvasz': true,
    'ovcharka': true,
    'caucasian': true,
    'wolfhound': true,
    'deerhound': true,
    'giant': true,
    'schnauzer': true,
    'bullterrier': true,
    'airedale': true,
    'pinscher': true,
    'african': true,
    'collie': true,
    'germanlonghair': true,
    'elkhound': true,
    'poodle': true
  }
};

// Sub-breed specific overrides for breeds with size variations
const SUB_BREED_OVERRIDES = {
  // Poodle size variations
  'poodle/toy': 'small',
  'poodle/miniature': 'small',
  'poodle/medium': 'medium',
  'poodle/standard': 'large',
  
  // Schnauzer size variations
  'schnauzer/miniature': 'small',
  'schnauzer/giant': 'large',
  
  // Pinscher size variations
  'pinscher/miniature': 'small',
  
  // Terrier size variations
  'terrier/toy': 'small',
  'terrier/yorkshire': 'small',
  'terrier/silky': 'small',
  'terrier/norfolk': 'small',
  'terrier/norwich': 'small',
  'terrier/cairn': 'small',
  'terrier/westhighland': 'small',
  'terrier/dandie': 'small',
  'terrier/lakeland': 'small',
  'terrier/sealyham': 'small',
  'terrier/tibetan': 'small',
  'terrier/bedlington': 'medium',
  'terrier/border': 'medium',
  'terrier/fox': 'small',
  'terrier/irish': 'medium',
  'terrier/kerryblue': 'medium',
  'terrier/patterdale': 'small',
  'terrier/russell': 'small',
  'terrier/scottish': 'small',
  'terrier/welsh': 'small',
  'terrier/wheaten': 'medium',
  'terrier/american': 'medium',
  'terrier/australian': 'small',
  'terrier/airedale': 'large',
  
  // Add more overrides as needed...
};

// Enhanced pattern-based fallback for breeds not in primary database
const SIZE_PATTERNS = {
  small: {
    high: ['toy', 'teacup', 'pocket', 'dwarf'],
    medium: ['mini', 'miniature', 'small', 'little', 'tiny'],
    low: ['lap', 'companion', 'indoor']
  },
  medium: {
    high: ['medium', 'standard'],
    medium: ['working', 'sporting', 'field'],
    low: ['regular', 'normal', 'average']
  },
  large: {
    high: ['giant', 'great', 'royal', 'maxi'],
    medium: ['large', 'big', 'heavy', 'bull', 'king'],
    low: ['guard', 'guardian', 'protection', 'mastiff']
  }
};

// Export for use in other modules
window.BreedData = {
  BREED_SIZE_DATABASE,
  SUB_BREED_OVERRIDES,
  SIZE_PATTERNS
};